type User {
  id: ID!
  username: String!
}

type Product {
  id: ID!
  name: String!
  description: String!
  stock: Int!
  price: Float!
}

type Order {
  id: ID!
  productId: ID!
  quantity: Int!
  status: String!
}

type Query {
  getUser(id: ID!): User
  getProduct(id: ID!): Product
  getOrder(id: ID!): Order
}

type Mutation {
  createUser(username: String!, password: String!): User
  createProduct(name: String!, stock: Int!, price: Float!): Product
  createOrder(productId: ID!, quantity: Int!): Order
  login(username: String!, password: String!): String
}
